#!/bin/bash

# Toggle the layout on the current active workspace between scrolling and master

ACTIVE_WORKSPACE=$(hyprctl activeworkspace -j | jq -r '.id')
CURRENT_LAYOUT=$(hyprctl activeworkspace -j | jq -r '.tiledLayout')

case "$CURRENT_LAYOUT" in
  scrolling) NEW_LAYOUT=master ;;
  *) NEW_LAYOUT=scrolling ;;
esac

hyprctl keyword workspace $ACTIVE_WORKSPACE, layout:$NEW_LAYOUT
notify-send "󱂬    Workspace layout set to $NEW_LAYOUT"
